import { useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";

const euro = (cents: number) => `${(cents / 100).toFixed(2).replace(".", ",")} €`;

type ProductStatus = "draft" | "active" | "archived";
type ProductForm = { sellerId: string; name: string; category: string; description: string; imageUrl: string; location: string; price: string };
const emptyForm: ProductForm = { sellerId: "1", name: "", category: "Automobile", description: "", imageUrl: "", location: "", price: "" };

export default function Admin() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  const isAdmin = user?.role === "admin";
  const orders = trpc.marketplace.adminOrders.useQuery(undefined, { enabled: isAdmin });
  const products = trpc.marketplace.adminProducts.useQuery(undefined, { enabled: isAdmin });
  const settings = trpc.marketplace.commissionSettings.useQuery(undefined, { enabled: isAdmin });
  const updateStatus = trpc.marketplace.updateCommissionStatus.useMutation({ onSuccess: () => orders.refetch() });
  const updateSetting = trpc.marketplace.updateCommissionSetting.useMutation({ onSuccess: () => settings.refetch() });
  const uploadProductImage = trpc.marketplace.uploadProductImage.useMutation({ onSuccess: (result) => setField("imageUrl", result.url) });
  const createProduct = trpc.marketplace.createProduct.useMutation({ onSuccess: async () => { setForm(emptyForm); setEditingId(null); await products.refetch(); } });
  const updateProduct = trpc.marketplace.updateProduct.useMutation({ onSuccess: async () => { setForm(emptyForm); setEditingId(null); await products.refetch(); } });
  const updateProductStatus = trpc.marketplace.updateProductStatus.useMutation({ onSuccess: () => products.refetch() });
  const [form, setForm] = useState<ProductForm>(emptyForm);
  const [editingId, setEditingId] = useState<number | null>(null);
  const feeCategories = [{ name: "Immobilier", seller: 250, buyer: 50 }, { name: "Automobile", seller: 400, buyer: 100 }, { name: "Luxe", seller: 800, buyer: 200 }, { name: "Transport", seller: 500, buyer: 100 }];
  const savedSettings = new Map((settings.data ?? []).map((setting) => [setting.category, setting]));

  if (loading) return <main className="admin-page"><p>Chargement…</p></main>;
  if (!isAuthenticated) return <main className="admin-page"><div className="admin-card"><p className="eyebrow">SITUN / OWNER ACCESS</p><h1>Connexion propriétaire.</h1><p>Connectez-vous avec le compte Manus qui a créé le projet SITUN pour gérer les annonces, les commandes et les commissions manuelles.</p><p className="admin-login-note">Utilisez le même compte que celui qui a créé le projet.</p><Button onClick={() => startLogin()}>Se connecter comme propriétaire</Button></div></main>;
  if (!isAdmin) return <main className="admin-page"><div className="admin-card"><p className="eyebrow">SITUN / OWNER ACCESS</p><h1>Accès réservé au propriétaire.</h1><p>Ce compte est connecté, mais il n’a pas les droits admin de SITUN. Déconnectez-vous et utilisez le compte qui a créé le projet.</p><div className="admin-actions"><Button onClick={() => logout()}>Changer de compte</Button><Link href="/"><Button variant="outline">Retourner à SITUN</Button></Link></div></div></main>;

  const setField = (key: keyof ProductForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const edit = (product: NonNullable<typeof products.data>[number]) => { setEditingId(product.id); setForm({ sellerId: String(product.sellerId), name: product.name, category: product.category, description: product.description ?? "", imageUrl: product.imageUrl ?? "", location: product.location ?? "", price: String(product.priceCents / 100) }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const handleImageChange = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) { event.target.value = ""; return; } if (file.size > 8 * 1024 * 1024) { event.target.value = ""; return; } const reader = new FileReader(); reader.onload = () => { const encoded = String(reader.result).split(",")[1] ?? ""; uploadProductImage.mutate({ fileName: file.name, contentType: file.type, base64: encoded }); }; reader.readAsDataURL(file); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const input = { sellerId: Number(form.sellerId), name: form.name.trim(), category: form.category.trim(), description: form.description.trim() || undefined, imageUrl: form.imageUrl.trim(), location: form.location.trim() || undefined, priceCents: Math.round(Number(form.price) * 100) }; if (editingId) updateProduct.mutate({ productId: editingId, ...input }); else createProduct.mutate({ ...input, status: "draft" }); };
  const cancelEdit = () => { setEditingId(null); setForm(emptyForm); };

  return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">SITUN / OWNER CONTROL</p><h1>Ghassen Ferjani</h1><p>Fondateur de SITUN · Gérez vos annonces, vos textes et votre réseau.</p></div><div className="admin-actions"><Link href="/"><Button variant="outline">Voir le site</Button></Link><Button variant="ghost" onClick={() => logout()}>Déconnexion</Button></div></header>
    <section className="admin-card listing-editor"><div className="admin-summary"><span>{editingId ? "Modifier l’annonce" : "Créer une annonce"}</span><strong>{editingId ? `#${editingId}` : "01"}</strong></div><p className="admin-help">Vous écrivez vous-même le titre et la description. Enregistrez d’abord en brouillon, puis publiez uniquement après avoir vérifié l’autorisation, le prix et la provenance.</p><form onSubmit={submit} className="listing-form"><label>Nom de l’annonce<input required minLength={2} value={form.name} onChange={(event) => setField("name", event.target.value)} placeholder="Ex. Villa avec vue sur le Ventoux" /></label><label>Catégorie<select value={form.category} onChange={(event) => setField("category", event.target.value)}><option>Automobile</option><option>Immobilier</option><option>Luxe</option><option>Transport</option><option>Mobilier</option><option>Maison</option><option>Mode</option><option>Électronique</option></select></label><label>Prix en euros<input required min="0.01" step="0.01" type="number" value={form.price} onChange={(event) => setField("price", event.target.value)} placeholder="0,00" /></label><label>Ville / localisation<input value={form.location} onChange={(event) => setField("location", event.target.value)} placeholder="Carpentras, Vaucluse" /></label><label className="listing-form-wide">Description<textarea required minLength={10} value={form.description} onChange={(event) => setField("description", event.target.value)} placeholder="Décrivez précisément le bien, son état, sa provenance et les conditions de contact." rows={5} /></label><label className="listing-form-wide image-upload-field">Photo de l’annonce<input type="file" accept="image/*" onChange={handleImageChange} disabled={uploadProductImage.isPending} /><small>{uploadProductImage.isPending ? "Téléversement en cours…" : "Choisissez n’importe quelle image depuis votre téléphone ou votre ordinateur (8 Mo maximum)."}</small>{form.imageUrl && <img className="image-preview" src={form.imageUrl} alt="Aperçu de l’annonce" />} {uploadProductImage.error && <small className="admin-error">Impossible de téléverser cette image. Vérifiez qu’il s’agit bien d’une image de 8 Mo maximum.</small>}</label><div className="listing-form-actions"><Button type="submit" disabled={createProduct.isPending || updateProduct.isPending}>{editingId ? "Enregistrer les modifications" : "Enregistrer en brouillon"}</Button>{editingId && <Button type="button" variant="outline" onClick={cancelEdit}>Annuler</Button>}</div>{(createProduct.error || updateProduct.error) && <p className="admin-error">Impossible d’enregistrer cette annonce : {(createProduct.error || updateProduct.error)?.message ?? "vérifiez les champs puis réessayez"}</p>}</form></section>
    <section className="admin-card"><div className="admin-summary"><span>Configuration des commissions</span><strong>{feeCategories.length}</strong></div><p className="admin-help">Modifiez les taux en points de base (100 = 1%). Aucun paiement automatique n’est déclenché.</p><div className="fee-settings">{feeCategories.map((category) => { const saved = savedSettings.get(category.name); return <div className="fee-row" key={category.name}><strong>{category.name}</strong><label>Vendeur <input type="number" min="0" max="5000" defaultValue={saved?.sellerRateBps ?? category.seller} onBlur={(event) => updateSetting.mutate({ category: category.name, sellerRateBps: Number(event.target.value), buyerRateBps: Number((event.currentTarget.parentElement?.parentElement?.querySelector("input[data-role=buyer]") as HTMLInputElement)?.value ?? category.buyer) })} /> /100%</label><label>Acheteur <input data-role="buyer" type="number" min="0" max="3000" defaultValue={saved?.buyerRateBps ?? category.buyer} onBlur={(event) => updateSetting.mutate({ category: category.name, sellerRateBps: Number((event.currentTarget.parentElement?.parentElement?.querySelector("input:not([data-role=buyer])") as HTMLInputElement)?.value ?? category.seller), buyerRateBps: Number(event.target.value) })} /> /100%</label></div>; })}</div></section>
    <section className="admin-card"><div className="admin-summary"><span>Commandes reçues</span><strong>{orders.data?.length ?? 0}</strong></div>{orders.isLoading ? <p>Chargement des commandes…</p> : orders.data?.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Commande</th><th>Client</th><th>Total</th><th>Revenu SITUN</th><th>Statut</th><th>Action</th></tr></thead><tbody>{orders.data.map((order) => <tr key={order.id}><td>#{order.id}</td><td>{order.customerName}<br /><small>{order.customerPhone}</small></td><td>{euro(order.subtotalCents + order.buyerFeeCents)}</td><td>{euro(order.commissionCents + order.buyerFeeCents)}</td><td><span className={`status-pill ${order.commissionCollectionStatus}`}>{order.commissionCollectionStatus}</span></td><td><select value={order.commissionCollectionStatus} onChange={(event) => updateStatus.mutate({ orderId: order.id, status: event.target.value as "pending" | "collected" | "waived" })} disabled={updateStatus.isPending}><option value="pending">pending</option><option value="collected">collected</option><option value="waived">waived</option></select></td></tr>)}</tbody></table></div> : <p className="admin-empty">لا توجد طلبات محفوظة حتى الآن.</p>}</section>
    <section className="admin-card"><div className="admin-summary"><span>Vos annonces</span><strong>{products.data?.length ?? 0}</strong></div>{products.isLoading ? <p>Chargement des annonces…</p> : products.data?.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Annonce</th><th>Catégorie</th><th>Prix</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{products.data.map((product) => <tr key={product.id}><td><strong>{product.name}</strong><br /><small>{product.location ?? "Localisation à préciser"}</small></td><td>{product.category}</td><td>{euro(product.priceCents)}</td><td><span className={`status-pill ${product.status}`}>{product.status}</span></td><td><div className="admin-row-actions"><Button variant="outline" size="sm" onClick={() => edit(product)}>Modifier</Button>{product.status === "active" ? <Button variant="ghost" size="sm" onClick={() => updateProductStatus.mutate({ productId: product.id, status: "draft" })}>Masquer</Button> : <Button size="sm" onClick={() => updateProductStatus.mutate({ productId: product.id, status: "active" })}>Publier</Button>}</div></td></tr>)}</tbody></table></div> : <p className="admin-empty">لا توجد إعلانات محفوظة حتى الآن. أنشئ أول إعلان من النموذج أعلاه.</p>}</section>
  </main>;
}
