import { Link } from "wouter";
import { useState } from "react";

type Language = "fr" | "ar" | "en";

const copy = {
  fr: { back: "Retour à SITUN", title: "Informations & confiance", intro: "SITUN facilite la mise en relation entre utilisateurs, acheteurs, vendeurs, prestataires et clients. La plateforme ne vend pas les biens présentés et ne garantit pas la conclusion, la qualité ou l’exécution d’une transaction.", terms: "Conditions d’utilisation", termsBody: "Les annonces sont publiées uniquement avec l’autorisation du professionnel ou du propriétaire. Le vendeur reste responsable de l’exactitude, de la provenance, de la disponibilité et de la conformité de son offre. SITUN facilite le premier contact ; le contrat, la négociation, les vérifications et la vente restent entre les parties concernées.", fees: "Rémunération transparente", feesBody: "Toute rémunération, commission ou prestation est définie par écrit avant la publication ou le début du service. Les conditions précisent qui paie et à quelle étape. SITUN ne collecte, ne conserve et ne traite pas automatiquement les paiements entre utilisateurs.", privacy: "Confidentialité", privacyBody: "Les informations transmises par formulaire servent à coordonner une demande et à contacter les parties concernées. SITUN ne demande pas de données inutiles. Ne transmettez jamais un mot de passe ou un code de vérification. Pour demander une correction ou une suppression, utilisez le canal de contact professionnel indiqué par SITUN.", contact: "Contactez SITUN", contactBody: "Assistance et demandes générales. Un compte WhatsApp Business officiel pourra être ajouté ultérieurement.", contactAction: "WhatsApp SITUN — bientôt disponible" },
  ar: { back: "العودة إلى SITUN", title: "المعلومات والثقة", intro: "يسهّل SITUN الربط بين المستخدمين والمشترين والبائعين ومقدمي الخدمات والعملاء. لا تبيع المنصة المنتجات المعروضة ولا تضمن إتمام المعاملة أو جودتها أو تنفيذها.", terms: "شروط الاستخدام", termsBody: "لا تُنشر الإعلانات إلا بإذن المهني أو المالك. يبقى البائع مسؤولًا عن صحة المعلومات والمصدر والتوفر والمطابقة. يسهّل SITUN التواصل الأول، بينما يبقى العقد والتفاوض والتحقق والبيع بين الأطراف المعنية.", fees: "أجر شفاف", feesBody: "يُحدد أي أجر أو عمولة أو خدمة كتابةً قبل النشر أو بدء الخدمة. وتوضح الشروط من يدفع ومتى تستحق الأجرة. لا يجمع SITUN المدفوعات بين المستخدمين ولا يحتفظ بها ولا يعالجها آليًا.", privacy: "الخصوصية", privacyBody: "تُستخدم البيانات المرسلة عبر النموذج لتنسيق الطلب والتواصل مع الأطراف المعنية. لا يطلب SITUN بيانات غير ضرورية. لا ترسل كلمة مرور أو رمز تحقق. لطلب التصحيح أو الحذف، استخدم قناة التواصل المهنية التي يحددها SITUN.", contact: "تواصل مع SITUN", contactBody: "للمساعدة والطلبات العامة. يمكن إضافة حساب WhatsApp Business رسمي مستقبلًا.", contactAction: "WhatsApp SITUN — متاح قريبًا" },
  en: { back: "Back to SITUN", title: "Information & trust", intro: "SITUN facilitates introductions between users, buyers, sellers, service providers and clients. The platform does not sell the goods shown and does not guarantee a transaction’s completion, quality or performance.", terms: "Terms of use", termsBody: "Listings are published only with the professional’s or owner’s permission. The seller remains responsible for accuracy, provenance, availability and compliance. SITUN facilitates the first introduction; the contract, negotiation, checks and sale remain between the relevant parties.", fees: "Transparent remuneration", feesBody: "Any fee, commission or service is defined in writing before publication or before the service begins. The terms identify who pays and when the fee is due. SITUN does not automatically collect, hold or process payments between users.", privacy: "Privacy", privacyBody: "Information sent through a form is used to coordinate a request and contact relevant parties. SITUN does not ask for unnecessary data. Never share a password or verification code. To request correction or deletion, use the professional contact channel identified by SITUN.", contact: "Contact SITUN", contactBody: "For assistance and general requests. An official WhatsApp Business account may be added later.", contactAction: "WhatsApp SITUN — coming soon" },
};

export default function Legal() {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = window.localStorage.getItem("situn-language");
    return saved === "ar" || saved === "en" ? saved : "fr";
  });
  const tx = copy[language];
  const chooseLanguage = (next: Language) => {
    window.localStorage.setItem("situn-language", next);
    setLanguage(next);
  };
  return <main className="legal-page" lang={language} dir={language === "ar" ? "rtl" : "ltr"}><header className="legal-header"><Link href="/" className="brand"><img className="brand-logo" src="/manus-storage/situn-user-logo_90e86129.jpg" alt="SITUN" /></Link><div className="language-switcher" aria-label="Choose language">{(["fr", "ar", "en"] as Language[]).map((item) => <button key={item} className={language === item ? "active" : ""} onClick={() => chooseLanguage(item)}>{item.toUpperCase()}</button>)}</div></header><div className="legal-inner"><Link href="/" className="legal-back">← {tx.back}</Link><p className="eyebrow">SITUN · WORLDWIDE</p><h1>{tx.title}</h1><p className="legal-intro">{tx.intro}</p><div className="legal-grid"><article><span>01</span><h2>{tx.terms}</h2><p>{tx.termsBody}</p></article><article><span>02</span><h2>{tx.fees}</h2><p>{tx.feesBody}</p></article><article><span>03</span><h2>{tx.privacy}</h2><p>{tx.privacyBody}</p></article><article><span>04</span><h2>{tx.contact}</h2><p>{tx.contactBody}</p><button className="gold-button" type="button" disabled>{tx.contactAction}</button></article></div></div></main>;
}
