import { Link } from "wouter";
import { useState } from "react";

type Language = "fr" | "ar" | "en";

const copy = {
  fr: { back: "Retour à SITUN", title: "Informations & confiance", intro: "SITUN est une plateforme indépendante de visibilité et de mise en relation. Elle ne vend pas les biens présentés et ne garantit pas la conclusion d’une transaction.", terms: "Conditions d’utilisation", termsBody: "Les annonces sont publiées uniquement avec l’autorisation du professionnel ou du propriétaire. Le vendeur reste responsable de l’exactitude, de la provenance, de la disponibilité et de la conformité de son offre. SITUN coordonne le premier contact ; le contrat, la négociation, la vérification et la vente restent entre les parties concernées.", fees: "Rémunération transparente", feesBody: "Tout frais de publication, de service ou d’apport est communiqué avant la mise en relation. Il est dû uniquement selon un accord écrit précisant qui paie — vendeur, acheteur ou les deux — et l’étape qui déclenche la rémunération. Aucun prélèvement automatique n’est réalisé par SITUN.", privacy: "Confidentialité", privacyBody: "Les informations transmises par téléphone, WhatsApp ou formulaire servent à coordonner la demande et à contacter les parties concernées. SITUN ne demande pas de données inutiles et ne recommande jamais de transmettre un mot de passe ou un code de vérification. Pour demander une correction ou une suppression, contactez le fondateur.", contact: "Contact propriétaire", contactBody: "Ghassen Ferjani — Fondateur de SITUN", contactAction: "Écrire sur WhatsApp" },
  ar: { back: "العودة إلى SITUN", title: "المعلومات والثقة", intro: "SITUN منصة مستقلة للظهور والربط التجاري. لا تبيع المنتجات المعروضة ولا تضمن إتمام الصفقة.", terms: "شروط الاستخدام", termsBody: "لا تُنشر الإعلانات إلا بإذن المهني أو المالك. يبقى البائع مسؤولًا عن صحة المعلومات والمصدر والتوفر والمطابقة. ينسق SITUN الاتصال الأول، بينما يبقى العقد والتفاوض والتحقق والبيع بين الأطراف المعنية.", fees: "أجر شفاف", feesBody: "يُبلّغ عن أي رسم نشر أو خدمة أو إحالة قبل الربط. ولا يستحق إلا وفق اتفاق مكتوب يحدد من يدفع — البائع أو المشتري أو كلاهما — والمرحلة التي تستحق عندها الأجرة. لا يخصم SITUN أموالًا تلقائيًا.", privacy: "الخصوصية", privacyBody: "تُستخدم البيانات التي ترسلها عبر الهاتف أو WhatsApp أو النموذج لتنسيق الطلب والتواصل مع الأطراف المعنية. لا يطلب SITUN بيانات غير ضرورية، ولا ترسل كلمة مرور أو رمز تحقق. لطلب التصحيح أو الحذف، تواصل مع المؤسس.", contact: "تواصل مع المالك", contactBody: "غسان فرجاني — مؤسس SITUN", contactAction: "الكتابة عبر WhatsApp" },
  en: { back: "Back to SITUN", title: "Information & trust", intro: "SITUN is an independent visibility and introduction platform. It does not sell the goods shown and does not guarantee that a transaction will be completed.", terms: "Terms of use", termsBody: "Listings are published only with the professional’s or owner’s permission. The seller remains responsible for accuracy, provenance, availability and compliance. SITUN coordinates the first introduction; the contract, negotiation, checks and sale remain between the relevant parties.", fees: "Transparent remuneration", feesBody: "Any listing, service or referral fee is disclosed before an introduction. It is due only under a written agreement identifying who pays — seller, buyer or both — and the trigger stage. SITUN does not process automatic deductions.", privacy: "Privacy", privacyBody: "Information sent by phone, WhatsApp or a form is used to coordinate the request and contact the relevant parties. SITUN does not ask for unnecessary data, and you should never share a password or verification code. To request correction or deletion, contact the founder.", contact: "Owner contact", contactBody: "Ghassen Ferjani — Founder of SITUN", contactAction: "Write on WhatsApp" },
};

export default function Legal() {
  const [language, setLanguage] = useState<Language>("fr");
  const tx = copy[language];
  return <main className="legal-page" lang={language} dir={language === "ar" ? "rtl" : "ltr"}><header className="legal-header"><Link href="/" className="brand"><span className="brand-mark">✦</span><span>SITUN</span></Link><div className="language-switcher">{(["fr", "ar", "en"] as Language[]).map((item) => <button key={item} className={language === item ? "active" : ""} onClick={() => setLanguage(item)}>{item.toUpperCase()}</button>)}</div></header><div className="legal-inner"><Link href="/" className="legal-back">← {tx.back}</Link><p className="eyebrow">SITUN · VAUCLUSE</p><h1>{tx.title}</h1><p className="legal-intro">{tx.intro}</p><div className="legal-grid"><article><span>01</span><h2>{tx.terms}</h2><p>{tx.termsBody}</p></article><article><span>02</span><h2>{tx.fees}</h2><p>{tx.feesBody}</p></article><article><span>03</span><h2>{tx.privacy}</h2><p>{tx.privacyBody}</p></article><article><span>04</span><h2>{tx.contact}</h2><p>{tx.contactBody}</p><a className="gold-button" href="https://wa.me/33602257226" target="_blank" rel="noreferrer">{tx.contactAction}</a></article></div></div></main>;
}
