import { useEffect } from "react";
import { ArrowRight, Flag, Globe2, MessageCircle } from "lucide-react";
import { Link, useRoute } from "wouter";
import { trpc } from "@/lib/trpc";
import { applySeo } from "@/lib/seo";
import { SITUN_WHATSAPP } from "@shared/marketplace";

const typeLabels: Record<string, string> = { product: "منتج", service: "خدمة", job: "فرصة عمل", online_work: "عمل عن بُعد", real_estate: "عقار", vehicle: "سيارة", classified: "إعلان" };

export default function PostDetail() {
  const [, params] = useRoute("/post/:id");
  const postId = Number(params?.id);
  const post = trpc.marketplace.post.useQuery({ postId }, { enabled: Number.isInteger(postId) && postId > 0 });
  useEffect(() => { if (!post.data) return; const title = `${post.data.title} | SITUN`; const description = post.data.description.slice(0, 155); const saved = window.localStorage.getItem("situn-language"); const language = saved === "ar" || saved === "fr" || saved === "en" ? saved : "en"; applySeo({ title, description, language, path: `/post/${post.data.id}`, image: post.data.imageUrl || undefined }); let script = document.querySelector('script[data-situn-post-schema]'); if (!script) { script = document.createElement("script"); script.setAttribute("type", "application/ld+json"); script.setAttribute("data-situn-post-schema", "true"); document.head.appendChild(script); } script.textContent = JSON.stringify({ "@context": "https://schema.org", "@type": post.data.postType === "job" || post.data.postType === "online_work" ? "JobPosting" : "Product", name: post.data.title, description: post.data.description, image: post.data.imageUrl || undefined, category: post.data.category, areaServed: [post.data.city, post.data.country].filter(Boolean).join(", ") || "Worldwide", offers: post.data.priceCents ? { "@type": "Offer", price: post.data.priceCents / 100, priceCurrency: post.data.currency, availability: "https://schema.org/InStock" } : undefined }); return () => { script?.remove(); }; }, [post.data]);
  if (post.isLoading) return <main className="section-page"><p className="section-empty">جاري تحميل المنشور...</p></main>;
  if (!post.data) return <main className="section-page"><div className="section-empty"><h1>المنشور غير متاح</h1><Link href="/marketplace">العودة إلى السوق</Link></div></main>;
  const item = post.data;
  return <main className="section-page marketplace-page" dir="rtl"><header className="section-header"><Link href="/" className="section-brand">✦ SITUN</Link><nav><Link href="/services">الخدمات والعمل</Link><Link href="/promotion">الترويج</Link><Link href="/marketplace">السوق العالمي</Link></nav><Link href="/workspace" className="section-profile">ملفي الشخصي</Link></header><article className="post-detail"><Link href="/marketplace" className="profile-back"><ArrowRight size={16} /> العودة إلى السوق</Link><div className="post-detail-grid">{item.imageUrl ? <img src={item.imageUrl} alt={item.title} /> : <div className="market-image-placeholder"><Globe2 size={42} /> SITUN</div>}<div><p className="section-kicker">{typeLabels[item.postType] ?? item.postType} · {item.city || item.country || "دولي"}</p><h1>{item.title}</h1><p className="post-detail-description">{item.description}</p><div className="post-detail-meta"><span>التصنيف: {item.category}</span><span>لغة المنشور: {item.language}</span>{item.priceCents ? <strong>{(item.priceCents / 100).toFixed(2)} {item.currency}</strong> : <strong>تواصل للسعر</strong>}</div><a className="section-gold-button" href={`https://wa.me/${SITUN_WHATSAPP}?text=${encodeURIComponent(`مرحبًا SITUN، أريد معلومات عن: ${item.title}`)}`} target="_blank" rel="noreferrer"><MessageCircle size={16} /> تواصل مع صاحب العرض</a><p className="post-detail-note">يرسل SITUN طلبك إلى إدارة الوساطة لتنسيق التواصل مع صاحب العرض أو المنشأة. تحقق من التفاصيل واتفق مع الطرف الآخر قبل أي التزام، وتُحدد العمولة كتابةً قبل المتابعة.</p></div></div></article><footer className="section-footer"><span>© SITUN · جميع الدول</span><span><Flag size={14} /> الإبلاغ عن محتوى مخالف من خلال التواصل مع الإدارة</span></footer></main>;
}
