import { useEffect } from "react";
import { ArrowRight, Flag, Globe2, MessageCircle } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { applySeo } from "@/lib/seo";
import { SITUN_WHATSAPP } from "@shared/marketplace";
import { useAuth } from "@/_core/hooks/useAuth";

const typeLabels = { fr: { product: "Produit", service: "Service", job: "Emploi", online_work: "Travail en ligne", real_estate: "Immobilier", vehicle: "Véhicule", classified: "Annonce" }, en: { product: "Product", service: "Service", job: "Job", online_work: "Online work", real_estate: "Real estate", vehicle: "Vehicle", classified: "Classified" }, ar: { product: "منتج", service: "خدمة", job: "فرصة عمل", online_work: "عمل عن بُعد", real_estate: "عقار", vehicle: "سيارة", classified: "إعلان" } } as const;
const detailCopy = { fr: { loading: "Chargement de l’annonce…", unavailable: "Annonce indisponible", back: "Retour à la marketplace", profile: "Mon profil", services: "Services & travail", promotion: "Promotion", market: "Marketplace mondiale", worldwide: "International", category: "Catégorie", language: "Langue de l’annonce", contactPrice: "Contacter pour le prix", contact: "Contacter l’auteur de l’offre", note: "SITUN facilite la mise en relation. Vérifiez les détails et convenez avec l’autre partie avant tout engagement ; les frais sont définis par écrit avant la suite.", report: "Signaler un contenu via l’administration" }, en: { loading: "Loading listing…", unavailable: "Listing unavailable", back: "Back to marketplace", profile: "My profile", services: "Services & work", promotion: "Promotion", market: "Global marketplace", worldwide: "Worldwide", category: "Category", language: "Listing language", contactPrice: "Contact for price", contact: "Contact the offer owner", note: "SITUN facilitates introductions. Check the details and agree with the other party before any commitment; fees are defined in writing before proceeding.", report: "Report content through administration" }, ar: { loading: "جاري تحميل المنشور...", unavailable: "المنشور غير متاح", back: "العودة إلى السوق", profile: "ملفي الشخصي", services: "الخدمات والعمل", promotion: "الترويج", market: "السوق العالمي", worldwide: "دولي", category: "التصنيف", language: "لغة المنشور", contactPrice: "تواصل للسعر", contact: "تواصل مع صاحب العرض", note: "يسهّل SITUN التعارف بين الأطراف. تحقق من التفاصيل واتفق مع الطرف الآخر قبل أي التزام، وتُحدد الرسوم كتابةً قبل المتابعة.", report: "الإبلاغ عن محتوى من خلال الإدارة" } } as const;

export default function PostDetail() {
  const [, params] = useRoute("/post/:id");
  const [, navigate] = useLocation();
  const { isAuthenticated } = useAuth();
  const postId = Number(params?.id);
  const post = trpc.marketplace.post.useQuery({ postId }, { enabled: Number.isInteger(postId) && postId > 0 });
  useEffect(() => { if (!post.data) return; const title = `${post.data.title} | SITUN`; const description = post.data.description.slice(0, 155); const saved = window.localStorage.getItem("situn-language"); const language = saved === "ar" || saved === "fr" || saved === "en" ? saved : "en"; applySeo({ title, description, language, path: `/post/${post.data.id}`, image: post.data.imageUrl || undefined }); let script = document.querySelector('script[data-situn-post-schema]'); if (!script) { script = document.createElement("script"); script.setAttribute("type", "application/ld+json"); script.setAttribute("data-situn-post-schema", "true"); document.head.appendChild(script); } script.textContent = JSON.stringify({ "@context": "https://schema.org", "@type": post.data.postType === "job" || post.data.postType === "online_work" ? "JobPosting" : "Product", name: post.data.title, description: post.data.description, image: post.data.imageUrl || undefined, category: post.data.category, areaServed: [post.data.city, post.data.country].filter(Boolean).join(", ") || "Worldwide", offers: post.data.priceCents ? { "@type": "Offer", price: post.data.priceCents / 100, priceCurrency: post.data.currency, availability: "https://schema.org/InStock" } : undefined }); return () => { script?.remove(); }; }, [post.data]);
  const savedLanguage = window.localStorage.getItem("situn-language");
  const language = savedLanguage === "ar" || savedLanguage === "fr" || savedLanguage === "en" ? savedLanguage : "en";
  const tx = detailCopy[language];
  const supportCopy = {
    fr: { title: "Bien communiquer et négocier", questions: ["Que comprend exactement l’offre ?", "Quel est le délai et le mode de livraison ?", "Le prix est-il fixe ou à convenir ?"], message: "Bonjour, je suis intéressé(e) par votre annonce. Pouvez-vous préciser ce qui est inclus, le délai et le prix final ?", copy: "Copier le message", copied: "Message copié" },
    en: { title: "Communicate and negotiate clearly", questions: ["What exactly is included?", "What is the timing and delivery method?", "Is the price fixed or open for discussion?"], message: "Hello, I am interested in your listing. Could you clarify what is included, the timing and the final price?", copy: "Copy message", copied: "Message copied" },
    ar: { title: "إرشادات للتواصل والتفاوض", questions: ["ماذا يشمل العرض بالتحديد؟", "ما المدة وطريقة التسليم؟", "هل السعر ثابت أم قابل للنقاش؟"], message: "مرحبًا، أنا مهتم بهذا المنشور. هل يمكن توضيح ما يشمله العرض والمدة والسعر النهائي؟", copy: "نسخ الرسالة", copied: "تم نسخ الرسالة" },
  }[language];
  const copyMessage = async () => { await navigator.clipboard?.writeText(supportCopy.message); toast.success(supportCopy.copied); };
  const startConversation = trpc.marketplace.startPostConversation.useMutation({ onSuccess: (conversation) => navigate(`/messages/${conversation.id}`), onError: (error) => toast.error(error.message) });
  const openDirectMessage = () => { if (!isAuthenticated) { navigate(`/auth?next=${encodeURIComponent(`/post/${postId}`)}`); return; } startConversation.mutate({ postId }); };

  if (post.isLoading) return <main className="section-page" lang={language} dir={language === "ar" ? "rtl" : "ltr"}><p className="section-empty">{tx.loading}</p></main>;
  if (!post.data) return <main className="section-page" lang={language} dir={language === "ar" ? "rtl" : "ltr"}><div className="section-empty"><h1>{tx.unavailable}</h1><Link href="/marketplace">{tx.back}</Link></div></main>;
  const item = post.data;
  return <main className="section-page marketplace-page" lang={language} dir={language === "ar" ? "rtl" : "ltr"}><header className="section-header"><Link href="/" className="section-brand">✦ SITUN</Link><nav><Link href="/services">{tx.services}</Link><Link href="/promotion">{tx.promotion}</Link><Link href="/marketplace">{tx.market}</Link></nav><Link href="/workspace" className="section-profile">{tx.profile}</Link></header><article className="post-detail"><Link href="/marketplace" className="profile-back"><ArrowRight size={16} /> {tx.back}</Link><div className="post-detail-grid">{item.imageUrl ? <img src={item.imageUrl} alt={item.title} /> : <div className="market-image-placeholder"><Globe2 size={42} /> SITUN</div>}<div><p className="section-kicker">{typeLabels[language][item.postType as keyof typeof typeLabels[typeof language]] ?? item.postType} · {item.city || item.country || tx.worldwide}</p><h1>{item.title}</h1><p className="post-detail-description">{item.description}</p><div className="post-detail-meta"><span>{tx.category}: {item.category}</span><span>{tx.language}: {item.language}</span>{item.priceCents ? <strong>{(item.priceCents / 100).toFixed(2)} {item.currency}</strong> : <strong>{tx.contactPrice}</strong>}</div><button className="section-gold-button" type="button" onClick={openDirectMessage} disabled={startConversation.isPending}><MessageCircle size={16} /> {language === "ar" ? "مراسلة مباشرة" : language === "en" ? "Message directly" : "Écrire directement"}</button><a className="section-outline-button" href={SITUN_WHATSAPP ? `https://wa.me/${SITUN_WHATSAPP}?text=${encodeURIComponent(supportCopy.message)}` : "#contact"}><MessageCircle size={16} /> {tx.contact}</a><aside className="communication-help"><p className="services-kicker"><MessageCircle size={15} /> {supportCopy.title}</p><ul>{supportCopy.questions.map((question) => <li key={question}>{question}</li>)}</ul><button className="outline-button" type="button" onClick={copyMessage}>{supportCopy.copy}</button></aside><p className="post-detail-note">{tx.note}</p></div></div></article><footer className="section-footer" id="contact"><span>© SITUN · {language === "ar" ? "جميع الدول" : language === "en" ? "Worldwide" : "Tous les pays"}</span><span><Flag size={14} /> {tx.report}</span></footer></main>;
}
