import { ArrowRight, Megaphone, UserCircle } from "lucide-react";
import { useEffect } from "react";
import { applySeo, SECTION_SEO } from "@/lib/seo";
import { Link } from "wouter";
import { SITUN_WHATSAPP } from "@shared/marketplace";

const whatsapp = (text: string) => SITUN_WHATSAPP ? `https://wa.me/${SITUN_WHATSAPP}?text=${encodeURIComponent(text)}` : "#contact";

const promotionCopy = {
  fr: { navServices: "Services & travail", navPromotion: "Promotion", navMarket: "Acheter & vendre", profile: "Mon profil", kicker: "Promotion et visibilité", title: "Montrez votre offre.", accent: "Attirez votre opportunité.", intro: "Que vous soyez prestataire, vendeur ou indépendant, SITUN vous aide à présenter votre offre clairement et à rencontrer les personnes qui cherchent à travailler ou acheter dans le monde entier.", cta: "Demander une promotion", offer: "Proposer mon savoir-faire", serviceTitle: "Promouvez un service", serviceText: "Présentez la programmation, la comptabilité, la formation, le design, le marketing, la rédaction ou tout savoir-faire utile.", serviceLink: "Ajouter votre service", productTitle: "Promouvez un produit", productText: "Envoyez les informations, les images et le prix de votre offre. Après examen, elle apparaît dans la marketplace.", productLink: "Voir la marketplace", profileTitle: "Promouvez votre profil", profileText: "Créez une page partageable réunissant votre présentation, vos langues et vos services publiés.", profileLink: "Créer votre profil", noteTitle: "Visibilité claire. Contact humain.", noteText: "La publication nécessite l’approbation du propriétaire. Aucun forfait ni tarif public fixe n’est affiché ; l’offre et les frais sont définis par écrit après contact, et SITUN ne traite pas les paiements.", home: "Accueil", worldwide: "Tous les pays", whatsappText: "Bonjour SITUN, je souhaite promouvoir un service ou un produit. Merci de m’expliquer les étapes et les frais." },
  en: { navServices: "Services & work", navPromotion: "Promotion", navMarket: "Buy & sell", profile: "My profile", kicker: "Promotion and visibility", title: "Show what you offer.", accent: "Attract your opportunity.", intro: "Whether you provide a service, sell a product or work independently, SITUN helps you present your offer clearly and reach people looking to work or buy worldwide.", cta: "Request promotion", offer: "Offer my skills", serviceTitle: "Promote a service", serviceText: "Present programming, accounting, education, design, marketing, writing or any useful skill.", serviceLink: "Add your service", productTitle: "Promote a product", productText: "Send your offer details, images and price. After review, it appears in the marketplace.", productLink: "View marketplace", profileTitle: "Promote your profile", profileText: "Create a shareable page bringing together your introduction, languages and published services.", profileLink: "Create your profile", noteTitle: "Clear visibility. Human contact.", noteText: "Publication requires owner approval. No fixed public package or advertising price is displayed; the offer and fees are defined in writing after contact, and SITUN does not process payments.", home: "Home", worldwide: "Worldwide", whatsappText: "Hello SITUN, I would like to promote a service or product. Please explain the steps and fees." },
  ar: { navServices: "الخدمات والعمل", navPromotion: "الترويج", navMarket: "التسوق والشراء", profile: "ملفي الشخصي", kicker: "قسم الترويج والظهور", title: "أظهر ما تقدّم.", accent: "واجذب فرصتك.", intro: "سواء كنت مقدم خدمة أو صاحب منتج أو مشروعًا مستقلًا، يساعدك SITUN على تقديم عرضك بوضوح والوصول إلى أشخاص يبحثون عن العمل والشراء حول العالم.", cta: "اطلب الترويج", offer: "أعرض مهارتي", serviceTitle: "روّج لخدمة", serviceText: "اعرض البرمجة، المحاسبة، التعليم، التصميم، التسويق، كتابة المحتوى أو أي حرفة يحتاجها الناس.", serviceLink: "أضف خدمتك", productTitle: "روّج لمنتج", productText: "أرسل معلومات عرضك وصورته وسعره. بعد المراجعة، يظهر في قسم التسوق والبيع والشراء.", productLink: "شاهد السوق", profileTitle: "روّج لملفك", profileText: "أنشئ صفحة شخصية قابلة للمشاركة تجمع نبذتك ولغاتك وخدماتك المنشورة.", profileLink: "أنشئ ملفك", noteTitle: "وصول أوضح. تواصل إنساني.", noteText: "يحتاج النشر إلى موافقة المالك، ولا توجد باقات أو أسعار إشهار ثابتة معروضة للعامة؛ يحدد العرض والعمولة كتابةً بعد التواصل، ولا تعالج SITUN المدفوعات.", home: "الصفحة الرئيسية", worldwide: "جميع الدول", whatsappText: "مرحبًا SITUN، أريد الترويج لخدمة أو منتج. أرجو شرح الخطوات والرسوم." },
} as const;

export default function Promotion() {
  const saved = window.localStorage.getItem("situn-language");
  const language = saved === "ar" || saved === "fr" || saved === "en" ? saved : "en";
  const tx = promotionCopy[language];
  useEffect(() => { applySeo({ ...SECTION_SEO.promotion[language], language, path: "/promotion" }); }, [language]);
  return <main className="section-page promotion-page" lang={language} dir={language === "ar" ? "rtl" : "ltr"}>
    <header className="section-header"><Link href="/" className="section-brand">✦ SITUN</Link><nav><Link href="/services">{tx.navServices}</Link><Link href="/promotion" className="active">{tx.navPromotion}</Link><Link href="/marketplace">{tx.navMarket}</Link></nav><Link href="/workspace" className="section-profile"><UserCircle size={17} /> {tx.profile}</Link></header>
    <section className="section-hero promotion-hero"><p className="section-kicker"><Megaphone size={15} /> {tx.kicker}</p><h1>{tx.title}<br /><em>{tx.accent}</em></h1><p>{tx.intro}</p><div className="section-actions"><a className="section-gold-button" href={whatsapp(tx.whatsappText)} target="_blank" rel="noreferrer">{tx.cta} <ArrowRight size={16} /></a><Link className="section-outline-button" href="/services">{tx.offer}</Link></div></section>
    <section className="promo-grid"><article><span>01</span><h2>{tx.serviceTitle}</h2><p>{tx.serviceText}</p><Link href="/services">{tx.serviceLink} <ArrowRight size={15} /></Link></article><article><span>02</span><h2>{tx.productTitle}</h2><p>{tx.productText}</p><Link href="/marketplace">{tx.productLink} <ArrowRight size={15} /></Link></article><article><span>03</span><h2>{tx.profileTitle}</h2><p>{tx.profileText}</p><Link href="/workspace">{tx.profileLink} <ArrowRight size={15} /></Link></article></section>
    <section className="section-note-band" id="contact"><strong>{tx.noteTitle}</strong><span>{tx.noteText}</span></section>
    <footer className="section-footer"><span>© SITUN · {tx.worldwide}</span><Link href="/services">{tx.navServices}</Link><Link href="/marketplace">{tx.navMarket}</Link><Link href="/">{tx.home}</Link></footer>
  </main>;
}
