import { useEffect, useMemo, useState } from "react";
import { applySeo, SECTION_SEO } from "@/lib/seo";
import { ArrowLeft, BriefcaseBusiness, Check, CircleUserRound, LogIn, MessageCircle, Plus, Search, ShieldCheck, Sparkles, X } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import CommissionNotice from "@/components/CommissionNotice";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { SITUN_WHATSAPP } from "@shared/marketplace";

const categories = ["Tous", "محاسبة", "تعليم عن بعد", "كتابة المحتوى", "إعداد CV", "برمجة", "إنشاء مواقع", "تصميم رقمي", "تسويق رقمي", "ترجمة", "مساعدة إدارية", "تجارة إلكترونية", "استشارات", "تنظيف", "إصلاح", "نقل وتوصيل", "تسوق", "رعاية", "جمال وعافية", "سيارات", "عقارات", "حرف ومهن", "أخرى"];
const categoryLabels: Record<SupportedLanguage, Record<string, string>> = {
  fr: { Tous: "Tous", "محاسبة": "Comptabilité", "تعليم عن بعد": "Formation à distance", "كتابة المحتوى": "Rédaction de contenu", "إعداد CV": "Création de CV", "برمجة": "Programmation", "إنشاء مواقع": "Création de sites", "تصميم رقمي": "Design numérique", "تسويق رقمي": "Marketing digital", "ترجمة": "Traduction", "مساعدة إدارية": "Assistance administrative", "تجارة إلكترونية": "E-commerce", "استشارات": "Conseil", "تنظيف": "Nettoyage", "إصلاح": "Réparation", "نقل وتوصيل": "Transport et livraison", "تسوق": "Shopping", "رعاية": "Aide à la personne", "جمال وعافية": "Beauté et bien-être", "سيارات": "Automobile", "عقارات": "Immobilier", "حرف ومهن": "Métiers et artisanat", "أخرى": "Autre" },
  en: { Tous: "All", "محاسبة": "Accounting", "تعليم عن بعد": "Online education", "كتابة المحتوى": "Content writing", "إعداد CV": "CV writing", "برمجة": "Programming", "إنشاء مواقع": "Websites", "تصميم رقمي": "Digital design", "تسويق رقمي": "Digital marketing", "ترجمة": "Translation", "مساعدة إدارية": "Administrative support", "تجارة إلكترونية": "E-commerce", "استشارات": "Consulting", "تنظيف": "Cleaning", "إصلاح": "Repairs", "نقل وتوصيل": "Transport & delivery", "تسوق": "Shopping", "رعاية": "Care", "جمال وعافية": "Beauty & wellness", "سيارات": "Vehicles", "عقارات": "Real estate", "حرف ومهن": "Trades", "أخرى": "Other" },
  ar: { Tous: "الكل", "محاسبة": "محاسبة", "تعليم عن بعد": "تعليم عن بعد", "كتابة المحتوى": "كتابة المحتوى", "إعداد CV": "إعداد السيرة الذاتية", "برمجة": "برمجة", "إنشاء مواقع": "إنشاء مواقع", "تصميم رقمي": "تصميم رقمي", "تسويق رقمي": "تسويق رقمي", "ترجمة": "ترجمة", "مساعدة إدارية": "مساعدة إدارية", "تجارة إلكترونية": "تجارة إلكترونية", "استشارات": "استشارات", "تنظيف": "تنظيف", "إصلاح": "إصلاح", "نقل وتوصيل": "نقل وتوصيل", "تسوق": "تسوق", "رعاية": "رعاية", "جمال وعافية": "جمال وعافية", "سيارات": "سيارات", "عقارات": "عقارات", "حرف ومهن": "حرف ومهن", "أخرى": "أخرى" }
};
const euro = (cents: number) => `${(cents / 100).toFixed(2).replace(".", ",")} €`;
const howCopy: Record<SupportedLanguage, { kicker: string; title: string; accent: string; steps: Array<{ title: string; text: string }>; ctaKicker: string; ctaText: string; countries: string }> = {
  fr: { kicker: "Comment ça marche", title: "Vous travaillez.", accent: "Nous rapprochons.", steps: [{ title: "Créez votre profil", text: "Présentez votre nom, votre savoir-faire et votre zone d’activité." }, { title: "Présentez votre service", text: "Décrivez clairement votre offre et son prix. Votre service est publié après son envoi." }, { title: "Échangez et convenez", text: "SITUN facilite le premier contact ; le contrat reste entre les parties." }], ctaKicker: "Indépendance et clarté", ctaText: "Plateforme indépendante. Publication, contact et commissions sont suivis clairement.", countries: "Tous les pays" },
  en: { kicker: "How it works", title: "You work.", accent: "We connect.", steps: [{ title: "Create your profile", text: "Present your name, expertise and service area." }, { title: "Offer your service", text: "Describe your offer and price clearly. your service is published after submission." }, { title: "Discuss and agree", text: "SITUN facilitates the first contact; the contract remains between the parties." }], ctaKicker: "Independence and clarity", ctaText: "Independent platform. Publication, approval, contact and commissions are tracked clearly.", countries: "All countries" },
  ar: { kicker: "كيف تعمل", title: "أنت تعمل.", accent: "ونحن نقرّب.", steps: [{ title: "أنشئ ملفك", text: "قدّم اسمك ومهارتك ونطاق عملك." }, { title: "اعرض خدمتك", text: "اكتب عرضك وسعرك بوضوح. تظهر خدمتك بعد إرسالها." }, { title: "تواصل واتفق", text: "يسهّل SITUN التواصل الأول، ويبقى العقد بين الأطراف." }], ctaKicker: "استقلال ووضوح", ctaText: "منصة مستقلة. تُتابع عملية النشر والموافقة والتواصل والعمولات بوضوح.", countries: "جميع الدول" }
};

type RequestForm = { name: string; phone: string; message: string };
type ProfileForm = { displayName: string; bio: string; location: string; country: string; languages: string };
type ServiceForm = { title: string; category: string; description: string; location: string; country: string; languages: string; deliveryMode: "online" | "local" | "hybrid"; price: string };

const emptyRequest: RequestForm = { name: "", phone: "", message: "" };
const emptyProfile: ProfileForm = { displayName: "", bio: "", location: "", country: "", languages: "" };
const emptyService: ServiceForm = { title: "", category: "Design numérique", description: "", location: "", country: "", languages: "", deliveryMode: "online", price: "" };

type SupportedLanguage = "fr" | "en" | "ar";
const serviceCopy: Record<SupportedLanguage, { navMarket: string; navPromotion: string; navServices: string; navHow: string; profile: string; share: string; kicker: string; title: string; accent: string; lead: string; offer: string; discover: string; noAuto: string; sectionKicker: string; sectionTitle: string; sectionAccent: string; search: string; reviewed: string; independent: string; noPayment: string; startProfile: string; requestTitle: string; requestName: string; requestPhone: string; requestMessage: string; requestSubmit: string; requestClose: string; requestSuccess: string; requestSuccessText: string }> = {
  fr: { navMarket: "Acheter", navPromotion: "Promotion", navServices: "Services & travail", navHow: "Comment ça marche", profile: "Mon profil", share: "Proposer mon savoir-faire", kicker: "MARKETPLACE INDÉPENDANTE", title: "Votre savoir-faire.", accent: "Votre opportunité.", lead: "Présentez vos compétences en ligne ou localement. SITUN facilite les introductions ; chaque partie choisit librement comment travailler et contracter.", offer: "Proposer un service", discover: "Découvrir les services", noAuto: "Mise en relation claire · rémunération convenue · aucun paiement automatique", sectionKicker: "SERVICES PUBLIÉS PAR LEURS PRESTATAIRES", sectionTitle: "Découvrez les", sectionAccent: "services", search: "Rechercher un service ou une compétence…", reviewed: "Les prestataires publient leurs services directement et restent responsables de leur contenu.", independent: "Plateforme indépendante.", noPayment: "Aucun paiement automatique.", startProfile: "Créer mon profil", requestTitle: "Demander un service", requestName: "Nom", requestPhone: "Téléphone ou WhatsApp", requestMessage: "Votre message", requestSubmit: "Envoyer la demande", requestClose: "Fermer", requestSuccess: "Demande envoyée", requestSuccessText: "Votre demande a été enregistrée. SITUN coordonnera le premier contact entre les parties." },
  en: { navMarket: "Buy", navPromotion: "Promotion", navServices: "Services & work", navHow: "How it works", profile: "My profile", share: "Offer my skills", kicker: "INDEPENDENT MARKETPLACE", title: "Your expertise.", accent: "Your opportunity.", lead: "Present your skills online or locally. SITUN facilitates introductions; each party freely chooses how to work and contract.", offer: "Offer a service", discover: "Discover services", noAuto: "Clear introductions · agreed remuneration · no automatic payment", sectionKicker: "SERVICES PUBLISHED BY PROVIDERS", sectionTitle: "Discover", sectionAccent: "services", search: "Search for a service or skill…", reviewed: "Providers publish their services directly and remain responsible for their content.", independent: "Independent platform.", noPayment: "No automatic payment processing.", startProfile: "Create my profile", requestTitle: "Request a service", requestName: "Name", requestPhone: "Phone or WhatsApp", requestMessage: "Your message", requestSubmit: "Send request", requestClose: "Close", requestSuccess: "Request sent", requestSuccessText: "Your request was recorded. SITUN will coordinate the first contact between the parties." },
  ar: { navMarket: "التسوق والشراء", navPromotion: "الترويج", navServices: "الخدمات والعمل", navHow: "كيف تعمل", profile: "ملفي الشخصي", share: "أشارك بمهارتي", kicker: "سوق مستقل", title: "مهارتك.", accent: "فرصتك.", lead: "اعرض مهاراتك عبر الإنترنت أو محليًا. يسهّل SITUN التعارف؛ ويختار كل طرف بحرية طريقة العمل والتعاقد.", offer: "أعرض خدمتي", discover: "اكتشف الخدمات", noAuto: "ربط واضح · أجر متفق عليه · لا معالجة دفع آلية", sectionKicker: "خدمات ينشرها مقدموها", sectionTitle: "اكتشف", sectionAccent: "الخدمات", search: "ابحث عن خدمة أو مهارة…", reviewed: "ينشر مقدمو الخدمات خدماتهم مباشرة ويتحملون مسؤولية محتواها.", independent: "منصة مستقلة.", noPayment: "لا معالجة دفع آلية.", startProfile: "أنشئ ملفي", requestTitle: "طلب خدمة", requestName: "الاسم", requestPhone: "الهاتف أو WhatsApp", requestMessage: "رسالتك", requestSubmit: "إرسال الطلب", requestClose: "إغلاق", requestSuccess: "تم إرسال الطلب", requestSuccessText: "تم تسجيل طلبك. سينسق SITUN التواصل الأول بين الأطراف." },
};

export default function Services() {
  const language = (window.localStorage.getItem("situn-language") === "en" ? "en" : window.localStorage.getItem("situn-language") === "ar" ? "ar" : "fr") as SupportedLanguage;
  const tx = serviceCopy[language];
  useEffect(() => { const saved = window.localStorage.getItem("situn-language"); const language = saved === "ar" || saved === "fr" || saved === "en" ? saved : "en"; applySeo({ ...SECTION_SEO.services[language], language, path: "/services" }); }, []);
  const { user, isAuthenticated } = useAuth();
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("Tous");
  const [requestId, setRequestId] = useState<number | null>(null);
  const [requestForm, setRequestForm] = useState<RequestForm>(emptyRequest);
  const [requestSent, setRequestSent] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [serviceOpen, setServiceOpen] = useState(false);
  const [profileForm, setProfileForm] = useState<ProfileForm>(emptyProfile);
  const [serviceForm, setServiceForm] = useState<ServiceForm>(emptyService);
  const [notice, setNotice] = useState("");
  const services = trpc.marketplace.services.useQuery();
  const profile = trpc.marketplace.profile.useQuery(undefined, { enabled: isAuthenticated });
  const myServices = trpc.marketplace.myServices.useQuery(undefined, { enabled: isAuthenticated });
  const saveProfile = trpc.marketplace.saveProfile.useMutation({ onSuccess: async () => { setProfileOpen(false); setNotice(language === "ar" ? "تم حفظ ملفك ويمكنك نشر خدماتك مباشرة." : language === "en" ? "Your profile is saved; you can publish services directly." : "Votre profil est enregistré ; vous pouvez publier vos services directement."); await profile.refetch(); } });
  const createService = trpc.marketplace.createService.useMutation({ onSuccess: async () => { setServiceOpen(false); setServiceForm(emptyService); setNotice(language === "ar" ? "تم نشر خدمتك بنجاح." : language === "en" ? "Your service was published successfully." : "Votre service a été publié avec succès."); await myServices.refetch(); } });
  const requestService = trpc.marketplace.requestService.useMutation({ onSuccess: (result) => { setRequestSent(true); setNotice("تم إرسال طلبك بنجاح. سيجري تنسيق التواصل مباشرة بين الأطراف عند توفر حساب WhatsApp Business الرسمي."); const service = services.data?.find((item) => item.service.id === requestId)?.service; const text = encodeURIComponent(`Bonjour SITUN, je souhaite demander le service « ${service?.title ?? "service"} ». Nom: ${requestForm.name}. Téléphone: ${requestForm.phone}. Message: ${requestForm.message}`); if (SITUN_WHATSAPP) window.open(`https://wa.me/${SITUN_WHATSAPP}?text=${text}`, "_blank", "noopener,noreferrer"); void result; } });

  const filtered = useMemo(() => (services.data ?? []).filter(({ service, profile: provider }) => {
    const haystack = `${service.title} ${service.description} ${service.category} ${service.location ?? ""} ${service.country ?? ""} ${service.languages ?? ""} ${provider?.displayName ?? ""}`.toLowerCase();
    return (category === "Tous" || service.category === category) && haystack.includes(query.toLowerCase());
  }), [services.data, category, query]);

  const openProfile = () => {
    if (!isAuthenticated) return window.location.assign(`/auth?next=${encodeURIComponent("/services")}`);
    setProfileForm({ displayName: profile.data?.displayName ?? user?.name ?? "", bio: profile.data?.bio ?? "", location: profile.data?.location ?? "", country: profile.data?.country ?? "", languages: profile.data?.languages ?? "" });
    setProfileOpen(true);
  };
  const openService = () => {
    if (!isAuthenticated) return window.location.assign(`/auth?next=${encodeURIComponent("/services")}`);
    if (!profile.data) { setNotice("أنشئ ملفك الشخصي أولًا، ثم أضف خدمتك."); setProfileOpen(true); return; }
    setServiceOpen(true);
  };
  const openRequest = (serviceId: number) => { setRequestId(serviceId); setRequestForm({ ...emptyRequest }); setRequestSent(false); };
  const submitRequest = (event: React.FormEvent) => { event.preventDefault(); if (requestId === null) return; requestService.mutate({ serviceId: requestId, buyerName: requestForm.name, buyerPhone: requestForm.phone, message: requestForm.message }); };
  const submitProfile = (event: React.FormEvent) => { event.preventDefault(); saveProfile.mutate(profileForm); };
  const submitService = (event: React.FormEvent) => { event.preventDefault(); createService.mutate({ ...serviceForm, priceCents: Math.round(Number(serviceForm.price) * 100) }); };

  return <main className="services-page" lang={language} dir={language === "ar" ? "rtl" : "ltr"}>
    <header className="services-header"><Link href="/" className="services-brand"><img className="brand-logo" src="/manus-storage/situn-user-logo_90e86129.jpg" alt="SITUN" /></Link><nav><Link href="/marketplace">{tx.navMarket}</Link><Link href="/promotion">{tx.navPromotion}</Link><a href="#services">{tx.navServices}</a><a href="#how">{tx.navHow}</a></nav><div className="services-header-actions"><button className="services-profile-button" onClick={openProfile}><CircleUserRound size={18} /> {isAuthenticated ? tx.profile : tx.share}</button>{isAuthenticated && <Link href="/workspace" className="admin-link">{language === "ar" ? "مساحة العمل" : language === "en" ? "Workspace" : "Espace de travail"}</Link>}{user?.role === "admin" && <Link href="/admin" className="admin-link">{language === "ar" ? "الإدارة" : language === "en" ? "Admin" : "Administration"}</Link>}</div></header>
    <section className="services-hero"><div className="services-hero-copy"><p className="services-kicker"><Sparkles size={15} /> {tx.kicker}</p><h1>{tx.title}<br /><em>{tx.accent}</em></h1><p className="services-lead">{tx.lead}</p><div className="services-hero-actions"><button className="services-gold-button" onClick={openService}><Plus size={17} /> {tx.offer}</button><a className="services-outline-button" href="#services">{tx.discover} <ArrowLeft size={17} /></a></div></div><div className="services-hero-card"><div className="services-card-mark">S<br />I<br />T<br />U<br />N</div><div><p>{language === "ar" ? "من الفكرة" : language === "en" ? "From an idea" : "De l’idée"}</p><strong>{language === "ar" ? "إلى الفرصة" : language === "en" ? "to an opportunity" : "à l’opportunité"}</strong><small>{tx.noAuto}</small></div></div></section>
    <CommissionNotice language={language} /><section className="services-ribbon"><span>{language === "ar" ? "أقدّم خدمة" : language === "en" ? "I offer a service" : "Je propose un service"}</span><b>{language === "ar" ? "أبحث عن خدمة" : language === "en" ? "I need a service" : "Je recherche un service"}</b><span>{language === "ar" ? "أعرض منتجًا" : language === "en" ? "I present a product" : "Je présente un produit"}</span><b>{language === "ar" ? "أريد الشراء" : language === "en" ? "I want to buy" : "Je souhaite acheter"}</b><span>{language === "ar" ? "وأبدأ عبر SITUN" : language === "en" ? "I start with SITUN" : "Je commence avec SITUN"}</span></section>
    <section className="services-content" id="services"><div className="services-section-heading"><div><p className="services-kicker">{tx.sectionKicker}</p><h2>{tx.sectionTitle} <em>{tx.sectionAccent}</em></h2></div><p>{tx.reviewed}</p></div><div className="services-toolbar"><div className="services-categories">{categories.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{categoryLabels[language][item] ?? item}</button>)}</div><label className="services-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={tx.search} /></label></div>{services.isLoading ? <div className="services-empty">{language === "ar" ? "جاري تحميل الخدمات..." : language === "en" ? "Loading services…" : "Chargement des services…"}</div> : filtered.length === 0 ? <div className="services-empty"><BriefcaseBusiness size={28} /><p>{language === "ar" ? "لا توجد خدمات منشورة بعد في هذا الاختيار." : language === "en" ? "No services have been published for this selection yet." : "Aucun service n’est encore publié pour cette sélection."}</p><button onClick={openService}>{language === "ar" ? "كن أول من يعرض خدمته" : language === "en" ? "Be the first to offer a service" : "Soyez le premier à proposer un service"}</button></div> : <div className="service-grid">{filtered.map(({ service, profile: provider }) => <article className="service-card" key={service.id}><div className="service-card-top"><span>{categoryLabels[language][service.category] ?? service.category}</span><b>{provider?.displayName?.slice(0, 1) ?? "S"}</b></div><h3>{service.title}</h3><p>{service.description}</p><div className="service-card-meta"><Link href={`/profile/${service.providerUserId}`} className="service-provider-link">{provider?.displayName ?? "Membre SITUN"}</Link>{service.country ? <span> · {service.country}</span> : service.location ? <span> · {service.location}</span> : null}<strong>{euro(service.priceCents)}</strong></div><small className="service-card-details">{service.deliveryMode === "online" ? (language === "ar" ? "عن بعد" : language === "en" ? "Online" : "En ligne") : service.deliveryMode === "local" ? (language === "ar" ? "حضوري" : language === "en" ? "In person" : "En présentiel") : (language === "ar" ? "عن بعد وحضوري" : language === "en" ? "Online & in person" : "En ligne & présentiel")}{service.languages ? ` · ${service.languages}` : ""}</small><button type="button" className="service-request-button" onPointerDown={() => openRequest(service.id)} onClick={() => openRequest(service.id)}>{language === "ar" ? "طلب هذه الخدمة" : language === "en" ? "Request this service" : "Demander ce service"} <MessageCircle size={16} /></button></article>)}</div>}</section>
    <section className="services-how" id="how"><div><p className="services-kicker">{howCopy[language].kicker}</p><h2>{howCopy[language].title}<br /><em>{howCopy[language].accent}</em></h2></div><div className="services-steps">{howCopy[language].steps.map((step, index) => <div key={step.title}><b>0{index + 1}</b><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section>
    <section className="services-cta"><ShieldCheck size={29} /><div><p className="services-kicker">{howCopy[language].ctaKicker}</p><h2>{tx.independent}<br /><em>{tx.noPayment}</em></h2><p>{howCopy[language].ctaText}</p></div><button className="services-gold-button" onClick={openProfile}><LogIn size={17} /> {tx.startProfile}</button></section>
    <footer className="services-footer"><span>© SITUN · {howCopy[language].countries}</span><Link href="/promotion">{tx.navPromotion}</Link><Link href="/marketplace">{tx.navMarket}</Link><Link href="/informations">{language === "ar" ? "المعلومات والشروط" : language === "en" ? "Information & terms" : "Informations & conditions"}</Link><Link href="/">{language === "ar" ? "الصفحة الرئيسية" : language === "en" ? "Home" : "Accueil"}</Link></footer>

    {requestId !== null && <div className="services-modal-backdrop" onClick={() => setRequestId(null)}><div className="services-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setRequestId(null)}><X /></button>{requestSent ? <div className="modal-success"><Check size={30} /><h2>{tx.requestSuccess}</h2><p>{tx.requestSuccessText}</p><button className="services-gold-button" onClick={() => setRequestId(null)}>{tx.requestClose}</button></div> : <><p className="services-kicker">{tx.requestTitle}</p><h2>{tx.requestTitle}</h2><form onSubmit={submitRequest} className="services-form"><label>{tx.requestName}<input required minLength={2} value={requestForm.name} onChange={(event) => setRequestForm({ ...requestForm, name: event.target.value })} /></label><label>{tx.requestPhone}<input required minLength={6} value={requestForm.phone} onChange={(event) => setRequestForm({ ...requestForm, phone: event.target.value })} /></label><label>{tx.requestMessage}<textarea rows={4} value={requestForm.message} onChange={(event) => setRequestForm({ ...requestForm, message: event.target.value })} placeholder={tx.requestMessage} /></label>{requestService.error && <p className="services-error">{language === "ar" ? "تعذر تسجيل الطلب. حاول مرة أخرى." : language === "en" ? "The request could not be recorded. Please try again." : "La demande n’a pas pu être enregistrée. Réessayez."}</p>}<button className="services-gold-button" disabled={requestService.isPending}>{requestService.isPending ? (language === "ar" ? "جارٍ الإرسال…" : language === "en" ? "Sending…" : "Envoi…") : tx.requestSubmit}</button></form></>}</div></div>}
    {profileOpen && <div className="services-modal-backdrop" onClick={() => setProfileOpen(false)}><div className="services-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setProfileOpen(false)}><X /></button><p className="services-kicker">ملفي الشخصي</p><h2>أظهر ما تستطيع.</h2><form onSubmit={submitProfile} className="services-form"><label>الاسم الظاهر<input required minLength={2} value={profileForm.displayName} onChange={(event) => setProfileForm({ ...profileForm, displayName: event.target.value })} placeholder="مثال: محمد — مصمم مستقل" /></label><label>المدينة أو المنطقة<input value={profileForm.location} onChange={(event) => setProfileForm({ ...profileForm, location: event.target.value })} placeholder="المدينة أو المنطقة أو عن بعد" /></label><label>الدولة<input value={profileForm.country} onChange={(event) => setProfileForm({ ...profileForm, country: event.target.value })} placeholder="مثال: France" /></label><label>اللغات التي تعمل بها<input value={profileForm.languages} onChange={(event) => setProfileForm({ ...profileForm, languages: event.target.value })} placeholder="العربية، Français، English" /></label><label>نبذة عنك<textarea required minLength={20} rows={5} value={profileForm.bio} onChange={(event) => setProfileForm({ ...profileForm, bio: event.target.value })} placeholder="ما الذي تتقنه؟ وما القيمة التي تقدمها؟" /></label>{saveProfile.error && <p className="services-error">تعذر حفظ الملف. تحقق من الحقول ثم حاول.</p>}<button className="services-gold-button" disabled={saveProfile.isPending}>{saveProfile.isPending ? "جارٍ الحفظ..." : "حفظ الملف"}</button></form></div></div>}
    {serviceOpen && <div className="services-modal-backdrop" onClick={() => setServiceOpen(false)}><div className="services-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setServiceOpen(false)}><X /></button><p className="services-kicker">عرض جديد</p><h2>حوّل مهارتك إلى فرصة.</h2><form onSubmit={submitService} className="services-form"><label>عنوان الخدمة<input required minLength={3} value={serviceForm.title} onChange={(event) => setServiceForm({ ...serviceForm, title: event.target.value })} placeholder="مثال: تصميم هوية بصرية" /></label><label>الفئة<select value={serviceForm.category} onChange={(event) => setServiceForm({ ...serviceForm, category: event.target.value })}>{categories.filter((item) => item !== "Tous").map((item) => <option key={item}>{item}</option>)}</select></label><label>السعر المعلن باليورو<input required min="1" step="0.01" type="number" value={serviceForm.price} onChange={(event) => setServiceForm({ ...serviceForm, price: event.target.value })} /></label><label>المكان أو المنطقة<input value={serviceForm.location} onChange={(event) => setServiceForm({ ...serviceForm, location: event.target.value })} placeholder="عن بعد أو المدينة" /></label><label>الدولة<input value={serviceForm.country} onChange={(event) => setServiceForm({ ...serviceForm, country: event.target.value })} placeholder="جميع الدول" /></label><label>لغات الخدمة<input value={serviceForm.languages} onChange={(event) => setServiceForm({ ...serviceForm, languages: event.target.value })} placeholder="العربية، Français، English" /></label><label>طريقة التقديم<select value={serviceForm.deliveryMode} onChange={(event) => setServiceForm({ ...serviceForm, deliveryMode: event.target.value as ServiceForm["deliveryMode"] })}><option value="online">عن بعد / عبر الإنترنت</option><option value="local">حضوري / محلي</option><option value="hybrid">عن بعد وحضوري</option></select></label><label>وصف الخدمة<textarea required minLength={20} rows={5} value={serviceForm.description} onChange={(event) => setServiceForm({ ...serviceForm, description: event.target.value })} placeholder="اشرح النتيجة التي سيحصل عليها العميل بوضوح." /></label>{createService.error && <p className="services-error">تعذر إرسال الخدمة. أنشئ ملفك أولًا وتحقق من البيانات.</p>}<button className="services-gold-button" disabled={createService.isPending}>{createService.isPending ? "جارٍ الإرسال..." : "نشر الخدمة"}</button></form></div></div>}
    {notice && <button className="services-notice" onClick={() => setNotice("")}>{notice} <X size={15} /></button>}
  </main>;
}

void SITUN_WHATSAPP;
