import { useEffect, useState } from "react";
import { ArrowRight, CircleUserRound, EyeOff, Globe2, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

const statusLabels = { fr: { draft: "Brouillon", pending: "En révision", active: "Publié", paused: "En pause", rejected: "Refusé", archived: "Archivé" }, en: { draft: "Draft", pending: "Under review", active: "Published", paused: "Paused", rejected: "Rejected", archived: "Archived" }, ar: { draft: "مسودة", pending: "قيد المراجعة", active: "منشور", paused: "متوقف", rejected: "مرفوض", archived: "مؤرشف" } } as const;
const typeLabels = { fr: { product: "Produit", service: "Service", job: "Emploi", online_work: "Travail en ligne", real_estate: "Immobilier", vehicle: "Véhicule", classified: "Annonce" }, en: { product: "Product", service: "Service", job: "Job", online_work: "Online work", real_estate: "Real estate", vehicle: "Vehicle", classified: "Classified" }, ar: { product: "منتج", service: "خدمة", job: "فرصة عمل", online_work: "عمل عن بُعد", real_estate: "عقار", vehicle: "سيارة", classified: "إعلان" } } as const;

type AccountType = "customer" | "seller" | "service_provider" | "employer" | "freelancer";

const workspaceCopy = {
  fr: { loading: "Ouverture de votre espace…", back: "Marché des services", kicker: "Mon espace SITUN", intro: "Gérez votre profil, vos services et vos annonces depuis un seul endroit.", posts: "Mes annonces", create: "Créer une annonce", manage: "Gestion des annonces", services: "Mes services", inquiries: "Demandes clients", settings: "Paramètres de mon compte", save: "Enregistrer mes paramètres", saving: "Enregistrement…", control: "Contrôle clair et respectueux", postsCount: "annonce(s)", servicesCount: "service(s)", inquiriesCount: "demande(s)", country: "Pays", city: "Ville", preferencesTitle: "Définissez votre usage de SITUN", preferencesText: "Ces informations aident SITUN à organiser les opportunités dans le monde.", emptyPosts: "Vous n’avez encore publié aucun contenu. Commencez par un produit, un service ou un emploi.", emptyServices: "Vos services apparaîtront ici lorsque vous en ajouterez un sur la marketplace.", emptyInquiries: "Les messages et demandes concernant vos annonces apparaîtront ici.", controlText: "Vous gérez votre contenu et pouvez le mettre en pause. Aucun paiement automatique ; les commissions sont suivies manuellement.", member: "Membre SITUN", post: "Annonce", addPost: "Ajouter une annonce", manageServices: "Gérer les services", serviceStatus: "Publié" },
  en: { loading: "Opening your workspace…", back: "Services marketplace", kicker: "My SITUN workspace", intro: "Manage your profile, services and listings from one place.", posts: "My listings", create: "Create a listing", manage: "Listing management", services: "My services", inquiries: "Client requests", settings: "My account settings", save: "Save my settings", saving: "Saving…", control: "Clear and respectful control", postsCount: "listings", servicesCount: "services", inquiriesCount: "requests", country: "Country", city: "City", preferencesTitle: "Define how you use SITUN", preferencesText: "This helps SITUN organize opportunities worldwide.", emptyPosts: "You have not published content yet. Start with a product, service or job.", emptyServices: "Your services will appear here when you add one from the services marketplace.", emptyInquiries: "Messages and requests from people interested in your listings will appear here.", controlText: "You manage your content and can pause it at any time. There are no automatic payments; commissions are tracked manually.", member: "SITUN member", post: "Listing", addPost: "Add a listing", manageServices: "Manage services", serviceStatus: "Published" },
  ar: { loading: "جاري فتح مساحتك...", back: "سوق الخدمات", kicker: "مساحتي في SITUN", intro: "أدر ملفك وخدماتك ومنشوراتك من مكان واحد.", posts: "منشوراتي", create: "إنشاء منشور", manage: "إدارة المنشورات", services: "خدماتي", inquiries: "طلبات العملاء", settings: "إعدادات حسابي", save: "حفظ إعداداتي", saving: "جارٍ الحفظ...", control: "تحكم واضح ومحترم", postsCount: "منشور", servicesCount: "خدمة", inquiriesCount: "طلب", country: "الدولة", city: "المدينة", preferencesTitle: "عرّف طريقة استعمالك للمنصة", preferencesText: "هذه المعلومات تساعد SITUN على تنظيم العروض حول العالم.", emptyPosts: "لم تنشر أي محتوى بعد. ابدأ بمنتج أو خدمة أو فرصة عمل.", emptyServices: "يمكنك الاحتفاظ بخدماتك الحالية أو إضافة خدمة جديدة من سوق الخدمات.", emptyInquiries: "ستظهر هنا رسائل وطلبات المهتمين بمنشوراتك.", controlText: "أنت تدير محتواك ويمكنك إيقافه في أي وقت. لا توجد مدفوعات آلية، وتتبع العمولة يتم يدويًا.", member: "عضو SITUN", post: "منشور", addPost: "إضافة منشور", manageServices: "إدارة الخدمات", serviceStatus: "منشور" },
} as const;

export default function Workspace() {
  const language = window.localStorage.getItem("situn-language") === "en" ? "en" : window.localStorage.getItem("situn-language") === "ar" ? "ar" : "fr";
  const tx = workspaceCopy[language];
  const { user, loading, isAuthenticated } = useAuth();
  const profile = trpc.marketplace.profile.useQuery(undefined, { enabled: isAuthenticated });
  const services = trpc.marketplace.myServices.useQuery(undefined, { enabled: isAuthenticated });
  const posts = trpc.marketplace.myPosts.useQuery(undefined, { enabled: isAuthenticated });
  const inquiries = trpc.marketplace.myInquiries.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const updateStatus = trpc.marketplace.updatePostStatus.useMutation({ onSuccess: () => utils.marketplace.myPosts.invalidate() });
  const deletePost = trpc.marketplace.deletePost.useMutation({ onSuccess: () => utils.marketplace.myPosts.invalidate() });
  const savePreferences = trpc.marketplace.updateUserPreferences.useMutation();
  const [accountType, setAccountType] = useState<AccountType>(user?.accountType ?? "customer");
  const [country, setCountry] = useState(user?.country ?? "");
  const [city, setCity] = useState(user?.city ?? "");
  const [preferredLanguage, setPreferredLanguage] = useState(user?.preferredLanguage ?? "ar");
  const [preferredCurrency, setPreferredCurrency] = useState(user?.preferredCurrency ?? "EUR");

  useEffect(() => { if (!loading && !isAuthenticated) window.location.href = "/auth?next=/workspace"; }, [loading, isAuthenticated]);
  if (loading || !isAuthenticated) return <main className="workspace-page" lang={language} dir={language === "ar" ? "rtl" : "ltr"}><p>{tx.loading}</p></main>;
  const remove = (postId: number) => { if (window.confirm(language === "ar" ? "هل تريد حذف هذا المنشور نهائيًا؟" : language === "en" ? "Delete this listing permanently?" : "Supprimer définitivement cette annonce ?")) deletePost.mutate({ postId }); };

  return (
    <main className="workspace-page" lang={language} dir={language === "ar" ? "rtl" : "ltr"}>
      <header className="profile-header">
        <Link href="/" className="services-brand"><span>✦</span> SITUN</Link>
        <Link href="/services" className="profile-back"><ArrowRight size={16} /> {tx.back}</Link>
      </header>
      <section className="workspace-hero">
        <div className="profile-avatar"><CircleUserRound size={32} /></div>
        <div><p className="services-kicker"><Globe2 size={15} /> {tx.kicker}</p><h1>{profile.data?.displayName ?? user?.name ?? tx.member}</h1><p>{tx.intro}</p></div>
      </section>
      <section className="workspace-grid">
        <div className="workspace-card workspace-card-wide"><div><p className="services-kicker">{tx.posts}</p><h2>{posts.data?.length ?? 0} {tx.postsCount}</h2><p>{language === "ar" ? "منتجات، خدمات، وظائف، عقارات، سيارات وإعلانات؛ كل منشور يمر بالمراجعة قبل ظهوره للعامة." : language === "en" ? "Products, services, jobs, real estate, vehicles and classifieds; every listing is reviewed before publication." : "Produits, services, emplois, immobilier, véhicules et annonces ; chaque annonce est examinée avant publication."}</p></div><Link href="/publish" className="services-gold-button"><Plus size={16} /> {tx.create}</Link></div>
        <div className="workspace-card"><p className="services-kicker">{tx.manage}</p>{posts.data?.length ? <div className="workspace-post-list">{posts.data.map((post) => <article className="workspace-post" key={post.id}><div><span className="workspace-post-type">{typeLabels[language][post.postType as keyof typeof typeLabels[typeof language]] ?? post.postType}</span><h3><Link href={`/publish/${post.id}`}>{post.title}</Link></h3><small>{post.country || (language === "ar" ? "دولي" : language === "en" ? "Worldwide" : "International")}{post.city ? ` · ${post.city}` : ""} · {post.currency}</small></div><div className="workspace-post-actions"><b className={`status-pill ${post.status}`}>{statusLabels[language][post.status as keyof typeof statusLabels[typeof language]] ?? post.status}</b>{post.status === "active" ? <button title={language === "ar" ? "إيقاف المنشور" : language === "en" ? "Pause listing" : "Mettre en pause"} onClick={() => updateStatus.mutate({ postId: post.id, status: "paused" })}><EyeOff size={15} /></button> : post.status === "paused" || post.status === "draft" ? <button title={language === "ar" ? "أرشفة المنشور" : language === "en" ? "Archive listing" : "Archiver l’annonce"} onClick={() => updateStatus.mutate({ postId: post.id, status: "archived" })}><EyeOff size={15} /></button> : null}<button className="danger-action" title={language === "ar" ? "حذف المنشور" : language === "en" ? "Delete listing" : "Supprimer l’annonce"} onClick={() => remove(post.id)}><Trash2 size={15} /></button></div></article>)}</div> : <p>{tx.emptyPosts}</p>}<Link href="/publish" className="services-outline-button"><Plus size={16} /> {tx.addPost}</Link></div>
        <div className="workspace-card"><p className="services-kicker">{tx.services}</p><h2>{services.data?.length ?? 0} {tx.servicesCount}</h2>{services.data?.length ? <div className="workspace-list">{services.data.map((service) => <div key={service.id}><span>{service.title}</span><b className={`status-pill ${service.status}`}>{statusLabels[language][service.status as keyof typeof statusLabels[typeof language]] ?? tx.serviceStatus}</b></div>)}</div> : <p>{tx.emptyServices}</p>}<Link href="/services" className="services-outline-button"><Plus size={16} /> {tx.manageServices}</Link></div>
        <div className="workspace-card workspace-card-wide"><div><p className="services-kicker">{tx.inquiries}</p><h2>{inquiries.data?.length ?? 0} {tx.inquiriesCount}</h2>{inquiries.data?.length ? <div className="workspace-list">{inquiries.data.slice(0, 5).map(({ inquiry, post }) => <div key={inquiry.id}><span>{inquiry.requesterName} · {post?.title ?? tx.post}</span><b className={`status-pill ${inquiry.status}`}>{statusLabels[language][inquiry.status as keyof typeof statusLabels[typeof language]] ?? inquiry.status}</b></div>)}</div> : <p>{tx.emptyInquiries}</p>}</div></div>
        <div className="workspace-card workspace-card-wide workspace-preferences"><div><p className="services-kicker">{tx.settings}</p><h2>{tx.preferencesTitle}</h2><p>{tx.preferencesText}</p></div><form className="workspace-preferences-form" onSubmit={(event) => { event.preventDefault(); savePreferences.mutate({ accountType, country: country || undefined, city: city || undefined, preferredLanguage, preferredCurrency }); }}><select value={accountType} onChange={(event) => setAccountType(event.target.value as AccountType)}><option value="customer">{language === "ar" ? "مشتري" : language === "en" ? "Customer" : "Acheteur"}</option><option value="seller">{language === "ar" ? "بائع" : language === "en" ? "Seller" : "Vendeur"}</option><option value="service_provider">{language === "ar" ? "مقدم خدمة" : language === "en" ? "Service provider" : "Prestataire"}</option><option value="employer">{language === "ar" ? "صاحب عمل" : language === "en" ? "Employer" : "Employeur"}</option><option value="freelancer">{language === "ar" ? "مستقل" : language === "en" ? "Freelancer" : "Freelance"}</option></select><input value={country} onChange={(event) => setCountry(event.target.value)} placeholder={tx.country} /><input value={city} onChange={(event) => setCity(event.target.value)} placeholder={tx.city} /><select value={preferredLanguage} onChange={(event) => setPreferredLanguage(event.target.value)}><option value="ar">العربية</option><option value="fr">Français</option><option value="en">English</option></select><select value={preferredCurrency} onChange={(event) => setPreferredCurrency(event.target.value)}><option value="EUR">EUR</option><option value="USD">USD</option><option value="GBP">GBP</option><option value="EGP">EGP</option><option value="TND">TND</option></select><button className="services-gold-button" type="submit" disabled={savePreferences.isPending}>{savePreferences.isPending ? tx.saving : tx.save}</button></form></div>
        <div className="workspace-card workspace-card-wide"><ShieldCheck size={22} /><div><h2>{tx.control}</h2><p>{tx.controlText}</p></div></div>
      </section>
      <footer className="services-footer"><span>© SITUN · {language === "ar" ? "جميع الدول" : language === "en" ? "Worldwide" : "Tous les pays"}</span><Link href="/profile/1">{language === "ar" ? "الملف العام" : language === "en" ? "Public profile" : "Profil public"}</Link></footer>
    </main>
  );
}
